spring.application.name=funding-service
server.port=9085

services.wallet.base-url=${WALLET_SERVICE_URL:http://localhost:9083}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

management.endpoints.web.exposure.include=health,info,prometheus
